"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.change_password = void 0;
exports.login = login;
exports.refresh = refresh;
exports.logout = logout;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
exports.change_password = __importStar(require("./change_password"));
/**
 * @controller AuthController.login
 * @path POST /auth/login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function login(connection, body) {
    return PlainFetcher_1.PlainFetcher.propagate({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json",
        },
    }, {
        ...login.METADATA,
        template: login.METADATA.path,
        path: login.path(),
    }, body);
}
(function (login) {
    login.METADATA = {
        method: "POST",
        path: "/auth/login",
        request: {
            type: "application/json",
            encrypted: false,
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 201,
    };
    login.path = () => "/auth/login";
})(login || (exports.login = login = {}));
/**
 * @controller AuthController.refresh
 * @path GET /auth/refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function refresh(connection) {
    return PlainFetcher_1.PlainFetcher.propagate(connection, {
        ...refresh.METADATA,
        template: refresh.METADATA.path,
        path: refresh.path(),
    });
}
(function (refresh) {
    refresh.METADATA = {
        method: "GET",
        path: "/auth/refresh",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 200,
    };
    refresh.path = () => "/auth/refresh";
})(refresh || (exports.refresh = refresh = {}));
/**
 * @controller AuthController.logout
 * @path POST /auth/logout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function logout(connection) {
    return PlainFetcher_1.PlainFetcher.propagate(connection, {
        ...logout.METADATA,
        template: logout.METADATA.path,
        path: logout.path(),
    });
}
(function (logout) {
    logout.METADATA = {
        method: "POST",
        path: "/auth/logout",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 201,
    };
    logout.path = () => "/auth/logout";
})(logout || (exports.logout = logout = {}));
