version: '3.8'

services:
  postgres:
    container_name: backoffice_postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-backoffice}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backoffice_network

  redis:
    container_name: backoffice_redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - backoffice_network

volumes:
  postgres_data:
  redis_data:

networks:
  backoffice_network:
    driver: bridge
    
