/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, IPropagation } from "@nestia/fetcher";
export * as auth from "./auth";
export * as users from "./users";
export * as roles from "./roles";
export * as transactions from "./transactions";
/**
 * @controller HomeController.getHello
 * @path GET /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getHello(connection: IConnection): Promise<getHello.Output>;
export declare namespace getHello {
    type Output = IPropagation<{
        200: string;
    }, 200>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 200;
    };
    const path: () => string;
}
