/**
 * @packageDocumentation
 * @module api.functional.auth.admin_register
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, IPropagation } from "@nestia/fetcher";
import type { AdminRegisterDTO } from "../../../structures/AdminRegisterDTO";
import type { FailedRequest } from "../../../structures/FailedRequest";
import type { SuccesfulRequestnull } from "../../../structures/SuccesfulRequestnull";
/**
 * @controller AuthController.adminRegister
 * @path POST /auth/admin-register
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function adminRegister(connection: IConnection, body: adminRegister.Input): Promise<adminRegister.Output>;
export declare namespace adminRegister {
    type Input = AdminRegisterDTO;
    type Output = IPropagation<{
        201: SuccesfulRequestnull | FailedRequest;
    }, 201>;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/auth/admin-register";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 201;
    };
    const path: () => string;
}
