"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminRegister = adminRegister;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller AuthController.adminRegister
 * @path POST /auth/admin-register
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function adminRegister(connection, body) {
    return PlainFetcher_1.PlainFetcher.propagate({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json",
        },
    }, {
        ...adminRegister.METADATA,
        template: adminRegister.METADATA.path,
        path: adminRegister.path(),
    }, body);
}
(function (adminRegister) {
    adminRegister.METADATA = {
        method: "POST",
        path: "/auth/admin-register",
        request: {
            type: "application/json",
            encrypted: false,
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 201,
    };
    adminRegister.path = () => "/auth/admin-register";
})(adminRegister || (exports.adminRegister = adminRegister = {}));
