"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAllPermissions = getAllPermissions;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller RoleController.getAllPermissions
 * @path GET /roles/all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function getAllPermissions(connection) {
    return PlainFetcher_1.PlainFetcher.propagate(connection, {
        ...getAllPermissions.METADATA,
        template: getAllPermissions.METADATA.path,
        path: getAllPermissions.path(),
    });
}
(function (getAllPermissions) {
    getAllPermissions.METADATA = {
        method: "GET",
        path: "/roles/all",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 200,
    };
    getAllPermissions.path = () => "/roles/all";
})(getAllPermissions || (exports.getAllPermissions = getAllPermissions = {}));
