/**
 * @packageDocumentation
 * @module api.functional.roles.all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, IPropagation } from "@nestia/fetcher";
import type { FailedRequest } from "../../../structures/FailedRequest";
import type { SuccesfulRequestArrayPermissionDTO } from "../../../structures/SuccesfulRequestArrayPermissionDTO";
/**
 * @controller RoleController.getAllPermissions
 * @path GET /roles/all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getAllPermissions(connection: IConnection): Promise<getAllPermissions.Output>;
export declare namespace getAllPermissions {
    type Output = IPropagation<{
        200: SuccesfulRequestArrayPermissionDTO | FailedRequest;
    }, 200>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/roles/all";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 200;
    };
    const path: () => string;
}
