"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findById = findById;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller UserController.findById
 * @path GET /users/:userId
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function findById(connection, targetUserId) {
    return PlainFetcher_1.PlainFetcher.propagate(connection, {
        ...findById.METADATA,
        template: findById.METADATA.path,
        path: findById.path(targetUserId),
    });
}
(function (findById) {
    findById.METADATA = {
        method: "GET",
        path: "/users/:userId",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 200,
    };
    findById.path = (targetUserId) => { var _a; return `/users/${encodeURIComponent((_a = targetUserId === null || targetUserId === void 0 ? void 0 : targetUserId.toString()) !== null && _a !== void 0 ? _a : "null")}`; };
})(findById || (exports.findById = findById = {}));
