"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findAll = findAll;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller UserController.findAll
 * @path GET /users/all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function findAll(connection) {
    return PlainFetcher_1.PlainFetcher.propagate(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(),
    });
}
(function (findAll) {
    findAll.METADATA = {
        method: "GET",
        path: "/users/all",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 200,
    };
    findAll.path = () => "/users/all";
})(findAll || (exports.findAll = findAll = {}));
