/**
 * @packageDocumentation
 * @module api.functional.users.all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, IPropagation } from "@nestia/fetcher";
import type { FailedRequest } from "../../../structures/FailedRequest";
import type { SuccesfulRequestArrayUserDTO } from "../../../structures/SuccesfulRequestArrayUserDTO";
/**
 * @controller UserController.findAll
 * @path GET /users/all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function findAll(connection: IConnection): Promise<findAll.Output>;
export declare namespace findAll {
    type Output = IPropagation<{
        200: SuccesfulRequestArrayUserDTO | FailedRequest;
    }, 200>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/users/all";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: 200;
    };
    const path: () => string;
}
