/**
 * @packageDocumentation
 * @module api.functional.auth.change_password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, IPropagation } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ChangePasswordDTO } from "../../../structures/ChangePasswordDTO";
import type { FailedRequest } from "../../../structures/FailedRequest";
import type { SuccesfulRequestnull } from "../../../structures/SuccesfulRequestnull";

/**
 * @controller AuthController.changePassword
 * @path POST /auth/change-password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function changePassword(
  connection: IConnection,
  body: changePassword.Input,
): Promise<changePassword.Output> {
  return PlainFetcher.propagate<any, any>(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...changePassword.METADATA,
      template: changePassword.METADATA.path,
      path: changePassword.path(),
    },
    body,
  );
}
export namespace changePassword {
  export type Input = ChangePasswordDTO;
  export type Output = IPropagation<
    {
      201: SuccesfulRequestnull | FailedRequest;
    },
    201
  >;

  export const METADATA = {
    method: "POST",
    path: "/auth/change-password",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/change-password";
}
