"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.changePassword = changePassword;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
/**
 * @controller AuthController.changePassword
 * @path POST /auth/change-password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function changePassword(connection, body) {
    return PlainFetcher_1.PlainFetcher.propagate({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json",
        },
    }, {
        ...changePassword.METADATA,
        template: changePassword.METADATA.path,
        path: changePassword.path(),
    }, body);
}
(function (changePassword) {
    changePassword.METADATA = {
        method: "POST",
        path: "/auth/change-password",
        request: {
            type: "application/json",
            encrypted: false,
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 201,
    };
    changePassword.path = () => "/auth/change-password";
})(changePassword || (exports.changePassword = changePassword = {}));
