"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.all = void 0;
exports.findAll = findAll;
exports.create = create;
exports.updatePermissions = updatePermissions;
const PlainFetcher_1 = require("@nestia/fetcher/lib/PlainFetcher");
exports.all = __importStar(require("./all"));
/**
 * @controller RoleController.findAll
 * @path GET /roles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function findAll(connection) {
    return PlainFetcher_1.PlainFetcher.propagate(connection, {
        ...findAll.METADATA,
        template: findAll.METADATA.path,
        path: findAll.path(),
    });
}
(function (findAll) {
    findAll.METADATA = {
        method: "GET",
        path: "/roles",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 200,
    };
    findAll.path = () => "/roles";
})(findAll || (exports.findAll = findAll = {}));
/**
 * @controller RoleController.create
 * @path POST /roles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function create(connection, createRoleDto) {
    return PlainFetcher_1.PlainFetcher.propagate({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json",
        },
    }, {
        ...create.METADATA,
        template: create.METADATA.path,
        path: create.path(),
    }, createRoleDto);
}
(function (create) {
    create.METADATA = {
        method: "POST",
        path: "/roles",
        request: {
            type: "application/json",
            encrypted: false,
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 201,
    };
    create.path = () => "/roles";
})(create || (exports.create = create = {}));
/**
 * @controller RoleController.updatePermissions
 * @path PATCH /roles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
async function updatePermissions(connection, updatePermissionsDto) {
    return PlainFetcher_1.PlainFetcher.propagate({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json",
        },
    }, {
        ...updatePermissions.METADATA,
        template: updatePermissions.METADATA.path,
        path: updatePermissions.path(),
    }, updatePermissionsDto);
}
(function (updatePermissions) {
    updatePermissions.METADATA = {
        method: "PATCH",
        path: "/roles",
        request: {
            type: "application/json",
            encrypted: false,
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 200,
    };
    updatePermissions.path = () => "/roles";
})(updatePermissions || (exports.updatePermissions = updatePermissions = {}));
